name: spring-batch-argo-workflow
services:
  sbaw-mysql:
    image: mysql:8.0
    container_name: sbaw-mysql
    ports:
      - "10001:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: general_user
      MYSQL_PASSWORD: passw0rd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

#  sbaw-app:
#    build:
#      context: ..
#      dockerfile: Dockerfile
#    container_name: sbaw-app
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_HIKARI_JDBC_URL: jdbc:mysql://sbaw-mysql:3306/demo
#      SPRING_DATASOURCE_HIKARI_USERNAME: general_user
#      SPRING_DATASOURCE_HIKARI_PASSWORD: passw0rd
#    depends_on:
#      sbaw-mysql:
#        condition: service_healthy
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 1G