apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-agent
  namespace: batch
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtasksets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtasksets/status"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-agent-binding
  namespace: batch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-agent
subjects:
  - kind: ServiceAccount
    name: default
    namespace: batch