apiVersion: v1
kind: Service
metadata:
  name: batch-api-server
  namespace: batch
  labels:
    app: batch-api-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: batch-api-server
