spring:
  datasource:
    url: jdbc:mysql://localhost:10100/jooq
    username: user
    password: passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jooq:
    sql-dialect: mysql

#logging:
#  level:
#    org.jooq.Constants: WARN
#